window.QUESTION_BANK = {
  "perception": [
    "What is the first thing you noticed about me?",
    "What do you think is the hardest part of what I do for a living?",
    "What reality show do you think I'm most likely to watch?",
    "Between the two of us, who seems like the better texter? Explain.",
    "What was your first impression of me?",
    "Finish the sentence: Just by looking at you, I'd think __________.",
    "Do I seem like someone who would get a name tattooed on myself? Why or why not?",
    "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
    "What about me intrigues you?",
    "What does my Instagram tell you about me?",
    "Do I seem like more of a creative or analytical type?",
    "What do my whose tell you about me?",
    "What subject do you think I thrived at in school and did I fail any?",
    "Do you think I fall in love easily? Why or why not?",
    "What do you think I'm most likely to splurge on?",
    "How many speeding tickets do you think I've gotten in my life?",
    "How would you describe what you think my type is in three words?",
    "Do you think I've ever been fired from a job? If so, what for?",
    "What did you think about my first message?",
    "What's one thing you'll never say no to?",
    "As a child, what do you think I wanted to be?",
    "Do I seem like a morning person or a night owl?",
    "Am I someone you typically connect with?",
    "Do you think I was popular in school? Explain.",
    "What compliment do you think I hear the most?",
    "What's one piece of advice that really stuck with you?",
    "What movie or book do you think I'm most like, and why?",
    "Do you think I'm usually early on time, or late to events? Explain.",
    "Do I intimidate you? Why or why not?",
    "What does my phone wallpaper tell you about me?",
    "Do you think I ever checked an Ex phone for evidence?",
    "Do I remind you of anyone you know?",
    "Something that brought a smile to my face this week was ______.",
    "What are your favorite song lyrics that come to your mind from the top of your head?",
    "What's one piece of advice that has really stuck with you?"
  ],
  "connection": [
    "Are you lying to yourself about anything?",
    "What questions are you trying to answer most in your life right now?",
    "What's been your happiest memory this past year?",
    "Have you changed your mind about anything recently?",
    "When was the last time you surprised yourself?",
    "How would you describe the feeling of being in love in one word?",
    "Has a stranger ever changed your life?",
    "What insecurity of yours holds you back the most?",
    "How could you become a better person?",
    "What title would you give this chapter in your life?",
    "What's the worst pain you have ever been in that wasn't physical?",
    "What is something you wouldn't want to change about yourself?",
    "What's your first love's name and the reason you fell in love with them?",
    "What would your younger self not believe about your life today?",
    "What's your mom's name and what is the most beautiful thing about her?",
    "What is a dream you let go of?",
    "If you could get to know someone in your life on a deeper level who would it be and why?",
    "What part of your life works, and what part of your life hurts?",
    "Do you think the image you have of yourself matches the image other people see you as?",
    "What's the nicest thing a friend (or partner) has ever done for you?",
    "What's the most embarrassing thing that happened to you on a date?",
    "What could you have done better in previous relationships?",
    "Do you think I intimidate others? Why or why not?",
    "When you are asked how are you, how often do you answer truthfully?",
    "How are you, really?",
    "What's your least favorite question to be asked on a date? What do you wish you would be asked more?",
    "What's the most unexplainable thing that happened to you?",
    "Describe your perfect day!",
    "What dating advice would you give your younger self?",
    "What did the people who raised you teach you about love?",
    "How old do you feel emotionally?",
    "Is there an image of yourself you try to project on a first date you wish you could let go of?",
    "What are you passionate about?",
    "Who's your comfort person?",
    "If you could have it your way: who would you be with? Where would you be? What would you be doing?",
    "If you had to choose a song that represents me, what would it be and why?",
    "What are you feeling a lot of today?",
    "What are you not currently giving enough time to?",
    "When was the last time you felt truly understood by somebody? Who was it? What did they understand?",
    "When was the last time you cried?"
  ],
  "reflection": [
    "What do you think my superpower is?",
    "Admit something.",
    "What about me surprised you?",
    "How would you describe me to a stranger?",
    "What do you think our most important similarities are?",
    "Based on what you learned about me, what would you recommend I read?",
    "What do you think is one thing I could do that would drastically improve my life?",
    "I want to give myself permission to feel ___________.",
    "What can I help you with?",
    "What do you think comes easily to me that's hard for others?",
    "What parts of yourself do you see in me?",
    "Where am I most qualified to give advice?",
    "What would be the perfect gift for me?",
    "What do I need to hear right now?",
    "What answer of mine made you light up?",
    "What question were you most afraid to answer?",
    "How does one earn your vulnerability?",
    "Based on what you've learned about me, does my social media portray me accurately?",
    "What would you remember about me if we ever cut contact?",
    "When this game is over, what will be something you will remember about me?",
    "What do you think my weakness is?",
    "What do you admire most about me?",
    "What's the most attractive quality about me that isn't physical?",
    "What can we create together?",
    "Dare your partner to do something out of their comfort zone next week.",
    "What is a lesson you will take away from our conversation?",
    "What do you think I fear the most?",
    "How can someone show you they love you, without saying the word?",
    "What do you recommend I should let go of?",
    "What about me is the hardest for you to understand?",
    "If we were a band, what would be our name?",
    "What has this conversation taught you about yourself?",
    "What do you think my defining characteristic is?",
    "What do you suggest I should let go of?",
    "Why do you think we met?",
    "How do our personalities complement each other?",
    "What are you still trying to prove to yourself?",
    "What do you think I should know about myself that perhaps I'm unaware of?",
    "What would make you feel closer to me?",
    "How do you think our lives would be different if we didn't meet?",
    "If you could pick one word to describe our connection, what would it be?",
    "What's something that reminds you of me?",
    "Do you think our connection has influenced your personal growth?",
    "Am I like you expected me to be?",
    "What do you think is the biggest obstacle in my life right now?",
    "In one word, describe how you feel now.",
    "Do you believe everyone has a calling? If so, do you think I've found mine?",
    "What do you think my defining characteristics are?",
    "What have you witnessed recently that has given you hope for humanity in any big or small way?",
    "What do you think is the biggest lesson I've taught you?",
    "What's a challenge you think we overcame together as a team?"
  ],
  "wildcard": [
    "Ask and answer the next question in a different accent.",
    "Write down the three most important things to you in a relationship (30 sec). Compare.",
    "Create your own question.",
    "Based on what you learned, re-write each other's daring app bios.",
    "Write down your number one goal for the next month. Compare.",
    "Write down a dating pet peeve (30 sec). Compare.",
    "Show each other pictures of when you were kids.",
    "Draw your current mood. Compare.",
    "Draw your favorite memory with me. Compare.",
    "Give your partner a compliment you don't think they hear enough.",
    "Ask a question you'd be too afraid to ask. Something you wouldn't dare to ask.",
    "Make an assumption about me.",
    "Write a message to each other on small pieces of paper, and open it after you've left."
  ]
};
