const questionBank = {
  food: [
    "What is your favorite thing to put ketchup on?",
    "What kind of food would you like to take a bath in?",
    "If you had to eat one food forever, what would it be?",
    "Ice cream, cake, or cookies?",
    "Best pizza topping?",
    "Best soup?",
    "Best ice cream sundae topping?",
    "If someone throws food at you, what do you choose?",
    "Magical food tree — what do you grow?",
    "Popsicle, pickle, or peanuts?",
    "Magical cupcakes — what power?",
    "Food for Thanksgiving?",
    "Something to put on toast?",
    "Something to put in a bath?",
    "Something you might eat in a sandwich",
    "Breakfast food kids love",
    "Something you might put on a hamburger",
    "Something that melts when hot",
  ],
  lifestyle: [
    "Best pet?",
    "Best subject?",
    "Dream car?",
    "Favorite book?",
    "Favorite TV show?",
    "Favorite sports team?",
    "Horse, motorcycle, or convertible?",
    "Unicorn, sloth, or dragon?",
    "Warm weather or snow forever?",
    "Favorite animal?",
    "Favorite playground activity?",
    "Best superhero?",
    "Best princess?",
    "Language you'd learn?",
    "Instrument you'd play?",
  ],
  general: [
    "Name a popular vacation destination",
    "Name a fruit for breakfast",
    "Name something people lose often",
    "Name a popular type of pie",
    "Name a type of flower",
    "Name a famous cartoon character",
    "Name something people fear",
    "Name a household chore",
    "Name a popular sport",
    "Name something people do to relax",
    "Name bedroom furniture",
    "Name a fast food chain",
    "Name a car brand",
    "Name a board game",
    "Name a social media platform",
    "Name a medical job",
    "Name a type of cake",
    "Name an injured body part",
    "Name a vegetable kids hate",
    "Name a fairy tale",
    "Name a holiday movie",
    "Name a shoe brand",
    "Name seafood",
    "Name a candy bar",
    "Name a hobby",
    "Name a cheese",
  ],
  objects: [
    "Something cold",
    "Something hot",
    "Rainbow color",
    "Something in space",
    "Something before bed",
    "Something to write with",
    "Something at the beach",
    "What people do when happy",
    "Transportation method",
    "Tree with fruit",
    "Christmas carol",
    "Job with a hat",
    "Something to climb",
    "Farm animal",
    "Garden plant",
    "Messy bedroom item",
  ],
  themed: [
    "Something related to vampires",
    "A house you don't want to be in",
    "Something worn for special events",
    "Wizard of Oz wish",
    "Something associated with pirates",
    "Something associated with princesses",
    "Something associated with Halloween",
    "Something in a haunted house",
  ],
  wordPrompts: [
    "Word that rhymes with \"honey\"",
    "Word that rhymes with \"power\"",
    "Something kids throw",
    "Something kids lose",
    "Place kids can't touch things",
    "Frozen character",
    "Homework excuse",
    "Something in a cave",
    "Something on a salad",
    "Star Wars character",
    "Something that comes in pairs",
    "Something scary in the dark",
    "Something you charge",
    "Something you wouldn't buy used",
  ],
  random: [
    "Dinosaur",
    "Something gross in restaurant food",
    "Bad pet animal",
    "Weekly activity",
    "Reason to be awake at 2am",
    "Spanish-speaking country",
    "Material for a treehouse",
    "Most expensive home item",
    "Something in the ocean",
    "Quiet pet animal",
    "Most important meal",
    "Type of ball",
    "Something good for environment",
    "Why teacher calls parents",
    "Card game",
    "Something in a deserted mansion",
    "Big US city",
    "Something you close eyes for",
    "Something scary in closet",
    "Something a bug does",
    "Something parents say don't touch",
    "Day you wake early",
    "Something on a treasure map",
    "What wakes you up",
    "Hokey Pokey action",
    "Sound near a barn",
  ],
}

export default questionBank
