const promptBank = {
  goodTruths: [
    "If you could be invisible for a day, what's the first thing you would do?",
    "What's the biggest secret you've kept from your parents?",
    "What's the most embarrassing music you listen to?",
    "What's one thing you love most about yourself?",
    "If a genie granted you three wishes, what would you ask for and why?",
    "Rom-coms or horror forever — which and why?",
    "Weirdest place you've gone to the bathroom?",
    "Have you ever ghosted someone?",
    "Who would survive a zombie apocalypse? Who wouldn't?",
    "What excuse have you used to get out of plans?",
    "Longest you've ever slept?",
    "Read your last text out loud.",
    "Biggest pet peeve?",
    "When was the last time you lied?",
    "Five things you'd bring to a deserted island?",
    "Most embarrassing thing on a date?",
    "Celebrity you resemble?",
    "How many selfies do you take daily?",
    "Something you'd wait an hour in line for?",
    "Longest without showering?",
    "Most embarrassing song on your phone?",
    "Favorite childhood show?",
    "If you changed your name, what would it be?",
    "Fictional character you'd be?",
    "Fictional character you'd date?",
    "One silly thing you can't live without?",
    "Favorite childhood vacation?",
    "Weirdest trend you followed?",
    "One song forever — what is it?",
    "Who do you text the most?",
    "Ever been fired?",
    "Flip-flops or heels for 10 years?",
    "Instant relationship dealbreaker?",
    "One food forever — what is it?",
    "Biggest lie to your parents?",
    "Worst physical pain?",
    "Who knows you best here?",
    "Favorite part of your body?",
    "Three life goals?",
    "Weirdest thing you've eaten?",
    "Ever gone skinny dipping?",
    "Biggest romantic fail?",
    "First celebrity crush?",
    "Strangest dream?",
    "Top 3 traits in a partner?",
    "Worst habit?",
    "How many stuffed animals do you own?",
    "Do you sleep with any?",
    "Biggest insecurity?",
    "What would you do with zero consequences?",
  ],
  deepTruths: [
    "Biggest regret?",
    "Most important lesson from parents?",
    "Who are you jealous of?",
    "Love at first sight — yes or no?",
    "Last time you cried?",
    "Biggest fear?",
    "Last time you apologized — for what?",
    "Any phobias?",
    "Believe in afterlife?",
    "What do you want to be remembered for?",
    "Do you believe in soulmates?",
    "Worst thing you've said to someone?",
    "Ever been rejected?",
    "Want to get married?",
    "What excites you most right now?",
    "What do you write about most privately?",
    "Afraid of the future?",
    "Ever ditched someone?",
    "Ever sabotaged someone?",
    "Ever lied to a friend?",
    "Said \"I love you\" without meaning it?",
    "How have your priorities changed?",
    "What would you do with $1M?",
    "Reconcile with an ex?",
    "One thing you'd do without consequences?",
    "More like your mom or dad?",
    "What are you most proud of?",
    "Bridges you're glad you burned?",
    "Biggest childhood fear?",
    "First heartbreak?",
    "Biggest mistake?",
    "Secret you've kept from your family?",
    "Worst thing done to you?",
    "Most painful experience?",
    "Something you're avoiding?",
    "Something you only do alone?",
    "Best compliment received?",
    "Scariest experience?",
    "Favorite possession?",
    "Marry for money without love?",
  ],
  spicyTruths: [
    "Secret crush?",
    "Last person you stalked online?",
    "First kiss story?",
    "Boldest pickup line used?",
    "Feelings for an ex?",
    "Ever sent a risky message?",
    "Celebrity hall pass?",
    "Unexpected attractive trait?",
    "Flirted with a friend's sibling?",
    "Wildest fantasy?",
    "Who would you kiss here?",
    "Date a friend's ex?",
    "Dream about someone here?",
    "Fake flirted for attention?",
    "Song that puts you in the mood?",
    "Caught feelings unexpectedly?",
    "Most spontaneous romantic act?",
    "\"No-questions-asked\" person?",
    "Outfit that makes you feel confident?",
    "Biggest dating dealbreaker?",
  ],
  easyDares: [
    "Roast someone for 1 minute.",
    "Let someone post for you on social media.",
    "Smell someone's armpit.",
    "Do a celebrity impression.",
    "Speak in an accent until next turn.",
    "Sing to someone dramatically.",
    "Show your best dance moves.",
    "Eat something weird (group chooses).",
    "Let someone redo your hairstyle.",
    "Do 20 squats.",
    "Prank call someone.",
    "Wear a silly hat made by others.",
    "Do a runway walk.",
    "Post your oldest selfie.",
    "Attempt a TikTok dance.",
    "Do karaoke.",
    "Describe everyone's best trait.",
    "Call a random number and talk for 1 minute.",
    "Send \"hey stranger\" to someone you haven't texted in a year.",
    "Reveal your screen time.",
  ],
  hardDares: [
    "Let someone send a text from your phone.",
    "Post a random photo to your story.",
    "Read your most personal text aloud.",
    "Call someone you haven't talked to in a year.",
    "Let others scroll your phone briefly.",
    "Text your crush something bold.",
    "Like an old post on your crush's profile.",
    "Eat a lemon slice without reacting.",
    "Yell your biggest fear outside.",
    "Perform a dramatic dance about your last relationship.",
    "Wear an outfit chosen by the group outside.",
    "Flirt seriously with someone for 3 rounds.",
    "Let the group blindfold and feed you something.",
    "Do a stand-up comedy set about your worst date.",
    "Write and perform a song about someone in the room.",
  ],
}

export default promptBank
