const promptBank = {
  truths: [
    // — Fun & Light —
    "If you could be invisible for a day, what's the first thing you'd do?",
    "What's the biggest secret you've kept from your parents?",
    "What's the most embarrassing music you actually listen to?",
    "What's one thing you love most about yourself?",
    "Have you ever ghosted someone?",
    "What excuse have you used to get out of plans?",
    "Read your last text out loud.",
    "What's something minor that can completely ruin your vibe — the kind of thing no one else quite gets?",
    "When was the last time you lied?",
    "What's the most embarrassing thing that happened to you on a date?",
    "What's the most unexpected thing someone did that made you immediately more attracted to them?",
    "What's a text you've been drafting but haven't sent — and why?",
    "Have you ever done something you knew was wrong just to keep someone happy?",
    "What's an instant relationship dealbreaker for you?",
    "What's the biggest lie you've told your parents?",
    "What's your favorite part of your own body?",
    "What's something you've never done that most people assume you have?",
    "Ever gone skinny dipping?",
    "What's your biggest romantic fail?",
    "What's the last thing you did that surprised even yourself?",
    "What's something you've outgrown that you haven't fully admitted yet?",
    "What are your top 3 traits in a partner?",
    "What's your worst habit?",
    "What's your biggest insecurity?",
    "What would you do if you had zero consequences for one day?",
    "What's an app on your phone you'd be embarrassed for someone to see?",
    "Have you ever sent a text to the wrong person? What did it say?",
    "What's a red flag you've ignored because you were too into someone?",
    "What's the pettiest reason you've ended or avoided something with someone?",
    "Have you ever pretended to like a gift? What was it?",
    "What's a habit you have that you hope no one knows about?",
    "What's something you've exaggerated to make a better first impression?",
    "Have you ever liked someone way longer than you should have?",
    "What's one opinion you have that most people would disagree with?",
    "What's the most embarrassing thing in your search history right now?",
    "What's the last thing you said that you immediately regretted?",
    "What's something you believe but are afraid to say out loud?",
    "What's the worst advice you've ever given someone?",
    // — Deep —
    "What's your biggest regret?",
    "What's the most important lesson your parents taught you?",
    "Who are you jealous of — and why?",
    "What's the most instantly you've ever felt drawn to someone — what was it about them that hit first?",
    "When was the last time you cried?",
    "What's something that scares you more than it probably should — something most people wouldn't guess about you?",
    "When was the last time you apologized — what for?",
    "What do you want to be remembered for?",
    "What do you think separates someone you love from someone you're genuinely meant to be with?",
    "What's the worst thing you've ever said to someone?",
    "Have you ever been rejected? How did you handle it?",
    "What excites you most in your life right now?",
    "What do you write about most when no one's watching?",
    "What's one thing about your future that genuinely scares you — be specific?",
    "Have you ever sabotaged someone?",
    "Have you ever said 'I love you' without meaning it?",
    "What are you most proud of in your life?",
    "What's a bridge you're glad you burned?",
    "What was your first heartbreak like?",
    "What's your biggest mistake?",
    "What's a secret you've kept from your family?",
    "What's the most painful experience you've been through?",
    "What are you avoiding right now?",
    "What's something you only do when you're completely alone?",
    "What's something you wish someone would just ask you about?",
    "Who in your life do you feel most misunderstood by?",
    "What's the hardest thing you've ever had to forgive someone for?",
    "What did your last relationship teach you about yourself?",
    "Have you ever been in love? Did the other person know?",
    "What's a version of yourself you've tried to leave behind?",
    "What's the most important thing you're not saying to someone right now?",
    "What do you think is the biggest thing standing between you and the life you want?",
    "What's something you've never said to your parents but wish you could?",
    "What's a relationship — romantic or not — you've never fully gotten over?",
    "What are you not giving enough time to right now?",
    "What's the one question you'd be most afraid to be asked right now?",
    "What's something you've tried to change about yourself but couldn't?",
    "What's something you want that you feel guilty for wanting?",
    // — Spicy & Romantic —
    "Who's your secret crush right now?",
    "Tell the story of your first kiss.",
    "Do you have feelings for an ex? Be honest.",
    "Have you ever sent a message you immediately regretted? What was it?",
    "Who would be your celebrity hall pass?",
    "What's your wildest fantasy — keep it PG-13.",
    "What's the boldest thing you've ever done to get someone's attention?",
    "Have you ever caught feelings for someone you shouldn't have?",
    "Who would be your 'no-questions-asked' person?",
    "What's the first physical thing you notice about someone you're attracted to?",
    "Have you thought about kissing anyone here tonight? Be honest.",
    "What's the most attractive thing someone has done in front of you recently?",
    "What's your love language — and do you think anyone here matches it?",
    "What does intimacy mean to you beyond the physical?",
    "What's something you want in a relationship that you're afraid to ask for?",
    "When was the last time someone made you feel truly desired?",
    "What makes someone genuinely irresistible to you — be specific?",
    "Have you ever ended something before it started because you were scared of how much you liked the person?",
    "If tonight were a date, how would it be going right now?",
    "What's a thought you've had about someone here tonight that you haven't said?",
    "What's the most reckless thing you've done for someone you were into?",
    "What do you think the energy in this room is right now?",
    "What does the way someone kisses tell you about them?",
    "What's a fantasy you've never shared with anyone?",
    "What's the most honest thing you can say out loud right now?",
  ],
  dares: [
    // — Fun & Social —
    "Do an impression of how you act when you're trying to impress someone — commit fully.",
    "Let someone here post something on your social media.",
    "Do your best celebrity impression.",
    "Speak in an accent until your next turn.",
    "Serenade someone in the room as dramatically as possible.",
    "Show your best dance moves for 30 seconds.",
    "Let someone redo your hairstyle.",
    "Prank call someone — keep it on speaker.",
    "Let someone in the room describe you to a stranger on the phone — listen without correcting them.",
    "Post your oldest selfie to your story right now.",
    "Attempt a TikTok dance from memory.",
    "Send 'hey stranger' to someone you haven't texted in a year.",
    "Reveal your screen time.",
    "Show everyone the most recent photo on your phone without editing.",
    "Describe every person in the room using only three words each.",
    "Open your notes app and read the first thing out loud.",
    "Show the most embarrassing photo on your phone — no scrolling allowed.",
    "Send a genuine compliment to someone you've been meaning to tell.",
    "Show everyone your camera roll from exactly one year ago.",
    "Do your best impression of someone else in the room.",
    "Show your most played song and explain why.",
    "Show the last meme you sent to someone.",
    "Call your mom or dad right now just to say you love them.",
    "Show your wallet or bag — everyone gets to ask about one thing in it.",
    "Let someone here read your most recent sent email or DM out loud.",
    "Tell everyone three things you think you have in common with someone here.",
    "Confess something you've been wanting to say but kept finding excuses not to.",
    "Let someone pick a contact from your phone and you have to tell the story of how you met.",
    "Play the most recent voice note or voice memo you've sent.",
    "Tell a 60-second story about the most spontaneous thing you've ever done.",
    "Let someone scroll your recent emoji keyboard and guess what your week was like.",
    "Show your most recent Google search — no closing tabs.",
    "Do a 60-second motivational speech about something completely insignificant.",
    "Recreate your most embarrassing moment in real time.",
    "Let someone here send one text from your phone — they choose who.",
    "Do an impression of how you think you look when you're flirting.",
    "Show someone your camera roll and let them ask about any photo they see.",
    "Do a dramatic 60-second retelling of your most embarrassing romantic moment.",
    "Act out your last text conversation without showing anyone the messages.",
    "Show the oldest message thread in your phone and read the first line.",
    "Show everyone your most-listened album this year and defend it seriously.",
    "Do a 30-second stand-up set about the most awkward thing that happened to you this week.",
    "Read your horoscope aloud and react like every word is devastating news.",
    "Let everyone ask your best friend one question about you over text right now.",
    "Read the last voice note or voice message you received out loud, acting it out.",
    // — Vulnerable & Intimate —
    "Tell the group something you've never said out loud before.",
    "Show a photo that means a lot to you and explain why.",
    "Describe a version of your future that excites and scares you equally.",
    "Share a childhood memory that still makes you smile.",
    "Describe the last person who made you feel truly seen.",
    "Tell everyone something you're quietly proud of that you almost never talk about.",
    "Read your most recent journal entry — or write one line right now and share it.",
    "Tell everyone what kind of person you're actively trying to become.",
    "Say something out loud that you normally only think.",
    "Tell someone in the room what you think their best quality is — the one they probably don't see themselves.",
    "Read your last 5 texts to your closest friend out loud.",
    "Tell everyone one thing you thought about someone here tonight that you haven't said.",
    "Say out loud what you think this night will be remembered for.",
    "Let someone ask you any one question and answer it with complete honesty.",
    "Tell the room one thing you've been carrying that you haven't shared with anyone.",
    "Describe the exact moment tonight you felt most present.",
    "Ask the question you've been holding back all night.",
    "Tell everyone what you wish someone here knew about you without you having to say it.",
    "Describe what you were like 5 years ago — and what you'd tell that version of yourself.",
    "Tell someone in the room what you think they need to hear right now.",
    "Share the most unexpectedly kind thing a stranger has ever done for you.",
    "Describe the person you were before your first heartbreak.",
    "Tell the group what your comfort zone is — and what lives just outside of it.",
    "Say the thing you've been avoiding saying to someone tonight.",
    "Tell everyone what you're most hoping happens before the night ends.",
    "Describe the energy you want the rest of tonight to have.",
    "Say out loud one thing you're grateful for that you don't say enough.",
    "Tell the person next to you one thing about them you genuinely admire.",
    // — Spicy & Romantic —
    "Compliment someone in the room in a way you think they've never been complimented before.",
    "Tell someone here exactly what went through your head when you first saw them tonight.",
    "Whisper something to the person across from you that you wouldn't say out loud.",
    "Look someone in the eyes and say one completely true thing to them.",
    "Without using the words 'beautiful' or 'attractive,' describe what you find appealing about someone here.",
    "Tell someone here what you'd do differently if you knew for certain they liked you.",
    "Describe what you think chemistry between two people feels like — physically.",
    "Sit closer than you'd normally sit to someone here. Hold that distance for two more turns.",
    "Give someone in the room a shoulder massage for 30 seconds.",
    "Let someone in the room fix something about how you look right now — hair, collar, anything.",
    "Describe your ideal first kiss — don't hold back.",
    "Make eye contact with someone here for 60 seconds without looking away or laughing.",
    "Tell someone in the room the most attractive thing they did or said tonight.",
    "Flirt seriously with the person across from you for the next 2 turns.",
    "Act out what your flirting looks like when you're really into someone — commit fully.",
    "Tell someone here one thing you'd do for them that you wouldn't do for most people.",
    "Write and perform a 30-second song about someone in the room.",
    "Ask someone here the question you've been most afraid to ask them.",
    "Tell someone in the room what you think they're like when they're in love.",
    "Describe the energy between you and one other person here right now.",
    "Tell someone here what you think they're searching for.",
    "Lean in and whisper a secret to someone in the room.",
    "Put your hand on someone's hand for 10 seconds without saying anything.",
    "Tell the person across from you one thing about them that you think most people miss.",
    "Tell everyone what you think the next 10 minutes should look like.",
    "Say something you'd only say if you were completely sure the other person felt the same way.",
    "Sit face to face with someone and describe everything you notice about them right now — out loud, no filter.",
    "Tell the person you're most drawn to tonight exactly why.",
  ],
}

export default promptBank
