const QUESTION_BANK = {
  "perception": [
    "What is the first thing you noticed about me?",
    "What do you think is the hardest part of what I do for a living?",
    "What reality show do you think I'm most likely to watch?",
    "Between the two of us, who seems like the better texter? Explain.",
    "What was your first impression of me?",
    "Finish the sentence: Just by looking at you, I'd think __________.",
    "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
    "What about me intrigues you?",
    "What does my Instagram tell you about me?",
    "Do I seem like more of a creative or analytical type?",
    "What subject do you think I thrived at in school and did I fail any?",
    "Do you think I fall in love easily? Why or why not?",
    "What do you think I'm most likely to splurge on?",
    "How would you describe what you think my type is in three words?",
    "What did you think about my first message?",
    "What do you think I'm like in an argument — do I fight or go quiet?",
    "As a child, what do you think I wanted to be?",
    "Am I someone you typically connect with?",
    "Do you think I was popular in school? Explain.",
    "What compliment do you think I hear the most?",
    "What movie or book do you think I'm most like, and why?",
    "Do I intimidate you? Why or why not?",
    "What does my phone wallpaper tell you about me?",
    "What do you think my relationship with money looks like?",
    "Do I remind you of anyone you know?",
    "Something that brought a smile to my face this week was ______.",
    "What emotion do you think I feel most often?",
    "Do you think I'm more guarded or more open than I appear?",
    "What's something you've noticed about me that you almost didn't say?",
    "If you had to guess what I'm most afraid of, what would it be?",
    "What do you think I look like when I'm completely at peace?",
    "What kind of person do you think I am when things go wrong?",
    "What do you think brings me the most joy in a regular day?",
    "What do you think I'm afraid to admit about myself?",
    "What do you think I'm like when I'm stressed?",
    "What do you think my relationship with my family is like?",
    "Do I seem like someone who holds grudges or lets things go?",
    "What do you think I was like as a teenager?",
    "Do you think I talk about my problems or keep them to myself?",
    "What's one thing you think would surprise me about you?",
    "Do you think I've ever had my heart broken? How do you think I handled it?",
    "Do I seem like the type to make the first move?",
    "What kind of friend do you think I am?",
    "What do you think I'm like when no one's watching?",
    "Do you think I'm more likely to say what I feel or keep it inside?",
    "If you had to guess one thing I'm insecure about, what would it be?",
    "What do you think I value more — stability or adventure?",
    "Do I seem like someone who needs a lot of alone time?",
    "What do you think I'm like the morning after a hard night?",
    "What's a song you think would be on my personal playlist?"
  ],
  "connection": [
    "Are you lying to yourself about anything?",
    "What questions are you trying to answer most in your life right now?",
    "What's been your happiest memory this past year?",
    "Have you changed your mind about anything recently?",
    "When was the last time you surprised yourself?",
    "How would you describe the feeling of being in love in one word?",
    "Has a stranger ever changed your life?",
    "What insecurity of yours holds you back the most?",
    "How could you become a better person?",
    "What title would you give this chapter in your life?",
    "What's the worst pain you have ever been in that wasn't physical?",
    "What is something you wouldn't want to change about yourself?",
    "What's your first love's name and the reason you fell in love with them?",
    "What would your younger self not believe about your life today?",
    "What's your mom's name and what is the most beautiful thing about her?",
    "What is a dream you let go of?",
    "If you could get to know someone in your life on a deeper level who would it be and why?",
    "What part of your life works, and what part of your life hurts?",
    "Do you think the image you have of yourself matches the image other people see you as?",
    "What's the nicest thing a friend (or partner) has ever done for you?",
    "What's the most embarrassing thing that happened to you on a date?",
    "What could you have done better in previous relationships?",
    "When you are asked how are you, how often do you answer truthfully?",
    "How are you, really?",
    "What's your least favorite question to be asked on a date? What do you wish you would be asked more?",
    "What's the most unexplainable thing that happened to you?",
    "Describe your perfect day!",
    "What dating advice would you give your younger self?",
    "What did the people who raised you teach you about love?",
    "How old do you feel emotionally?",
    "Is there an image of yourself you try to project on a first date you wish you could let go of?",
    "What's something you care deeply about that you rarely get to talk about?",
    "Who's your comfort person?",
    "If you could have it your way: who would you be with? Where would you be? What would you be doing?",
    "If you had to choose a song that represents me, what would it be and why?",
    "What are you feeling a lot of today?",
    "What are you not currently giving enough time to?",
    "When was the last time you felt truly understood by somebody? Who was it? What did they understand?",
    "When was the last time you cried?",
    "What's something you know is good for you but keep avoiding?",
    "Who in your life have you never fully forgiven — including yourself?",
    "What's the version of yourself you're most proud of?",
    "What's something you used to believe about love that you no longer do?",
    "If you could have one conversation back with anyone, who would it be and what would you say?",
    "What's the part of your story you rarely tell people?",
    "What would you do differently if you knew no one would judge you?",
    "What's something you've never been asked that you've always wanted to answer?",
    "When did you last feel completely free? What were you doing?",
    "What's a belief you hold that most people close to you don't know about?",
    "What's the most alive you've ever felt?"
  ],
  "reflection": [
    "What do you think my superpower is?",
    "Admit something.",
    "What about me surprised you?",
    "How would you describe me to a stranger?",
    "What do you think our most important similarities are?",
    "Based on what you learned about me, what would you recommend I read?",
    "What do you think is one thing I could do that would drastically improve my life?",
    "I want to give myself permission to feel ___________.",
    "What can I help you with?",
    "What do you think comes easily to me that's hard for others?",
    "What parts of yourself do you see in me?",
    "Where am I most qualified to give advice?",
    "What would be the perfect gift for me?",
    "What do I need to hear right now?",
    "What answer of mine made you light up?",
    "What question were you most afraid to answer?",
    "How does one earn your vulnerability?",
    "Based on what you've learned about me, does my social media portray me accurately?",
    "What would you remember about me if we ever cut contact?",
    "When this game is over, what will be something you will remember about me?",
    "What do you think my weakness is?",
    "What do you admire most about me?",
    "What's the most attractive quality about me that isn't physical?",
    "Dare your partner to do something out of their comfort zone next week.",
    "What is a lesson you will take away from our conversation?",
    "What do you think I fear the most?",
    "How can someone show you they love you, without saying the word?",
    "What do you recommend I should let go of?",
    "What about me is the hardest for you to understand?",
    "What has this conversation taught you about yourself?",
    "What do you think my defining characteristic is?",
    "Why do you think we met?",
    "How do our personalities complement each other?",
    "What are you still trying to prove to yourself?",
    "What do you think I should know about myself that perhaps I'm unaware of?",
    "What would make you feel closer to me?",
    "How do you think our lives would be different if we didn't meet?",
    "If you could pick one word to describe our connection, what would it be?",
    "What's something that reminds you of me?",
    "Do you think our connection has influenced your personal growth?",
    "Am I like you expected me to be?",
    "What do you think is the biggest obstacle in my life right now?",
    "Do you believe everyone has a calling? If so, do you think I've found mine?",
    "What have you witnessed recently that has given you hope for humanity in any big or small way?",
    "What do you think is the biggest lesson I've taught you?",
    "What do you think I'm searching for?",
    "Do you think we'd be good for each other? Why or why not?",
    "What's something about our conversation you didn't expect?",
    "What's the most honest thing you could say to me right now?",
    "What do you think I'm afraid to want?"
  ],
  "wildcard": [
    "Ask and answer the next question in a different accent.",
    "Write down the three most important things to you in a relationship (30 sec). Compare.",
    "Create your own question.",
    "Based on what you learned, re-write each other's dating app bios.",
    "Write down your number one goal for the next month. Compare.",
    "Write down a dating pet peeve (30 sec). Compare.",
    "Show each other pictures of when you were kids.",
    "Draw your current mood. Compare.",
    "Draw your favorite memory with me. Compare.",
    "Give your partner a compliment you don't think they hear enough.",
    "Ask a question you'd be too afraid to ask. Something you wouldn't dare to ask.",
    "Make an assumption about me.",
    "Write a message to each other on small pieces of paper, and open it after you've left.",
    "Swap phones for 5 minutes. No restrictions.",
    "Write down what you think the other person needs most right now. Share at the same time.",
    "Take a photo together right now. Don't pose.",
    "Tell each other one thing you noticed tonight that you haven't mentioned yet.",
    "Write down one word that describes this conversation. Compare.",
    "Show each other your lock screen. Explain what it says about where you are in life right now.",
    "Text someone you've both been meaning to reach out to — do it together, right now."
  ]
};

export default QUESTION_BANK;
